/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const APIWoundMeasurement = IDL.Record({
  'circularity' : IDL.Float64,
  'redPercentage' : IDL.Float64,
  'area' : IDL.Float64,
  'perimeter' : IDL.Float64,
  'diagnosis' : IDL.Text,
  'textureSmoothness' : IDL.Float64,
  'exudateLevel' : IDL.Float64,
  'timestamp' : IDL.Int,
  'edgeSharpness' : IDL.Float64,
  'image' : ExternalBlob,
  'blackPercentage' : IDL.Float64,
  'yellowPercentage' : IDL.Float64,
  'pinkPercentage' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'deleteMeasurement' : IDL.Func([IDL.Text], [], []),
  'getAllMeasurements' : IDL.Func(
      [],
      [IDL.Vec(APIWoundMeasurement)],
      ['query'],
    ),
  'getMeasurement' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(APIWoundMeasurement)],
      ['query'],
    ),
  'measureWound' : IDL.Func(
      [
        IDL.Text,
        ExternalBlob,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [APIWoundMeasurement],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const APIWoundMeasurement = IDL.Record({
    'circularity' : IDL.Float64,
    'redPercentage' : IDL.Float64,
    'area' : IDL.Float64,
    'perimeter' : IDL.Float64,
    'diagnosis' : IDL.Text,
    'textureSmoothness' : IDL.Float64,
    'exudateLevel' : IDL.Float64,
    'timestamp' : IDL.Int,
    'edgeSharpness' : IDL.Float64,
    'image' : ExternalBlob,
    'blackPercentage' : IDL.Float64,
    'yellowPercentage' : IDL.Float64,
    'pinkPercentage' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'deleteMeasurement' : IDL.Func([IDL.Text], [], []),
    'getAllMeasurements' : IDL.Func(
        [],
        [IDL.Vec(APIWoundMeasurement)],
        ['query'],
      ),
    'getMeasurement' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(APIWoundMeasurement)],
        ['query'],
      ),
    'measureWound' : IDL.Func(
        [
          IDL.Text,
          ExternalBlob,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [APIWoundMeasurement],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };